## Travis CI configuration
## See https://docs.travis-ci.com/user/languages/r/ for details

language: r
cache: packages
r:
  - oldrel
  - release
  - devel

warnings_are_errors: false

env:
  global:
    - _R_CHECK_CRAN_INCOMING_=FALSE

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); codecov()'
